---
- name: Logstash | Add GPG Key
  rpm_key:
    key: "{{ ls_yum_repo_gpgkey }}"
    state: present

- name: Logstash | Add Repository
  template:
    src: elastic.repo.j2
    dest: /etc/yum.repos.d/elastic.repo
    owner: root
    group: root
    mode: 0644

- name: Logstash | Install Packages
  package:
    name: logstash
    state: present

- name: Logstash | Configure Service
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
    owner: logstash
    group: logstash
    mode: 0660
  notify: restart logstash

- name: Logstash | Collect Own Logs
  template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/10-logstash.conf
    owner: logstash
    group: logstash
    mode: 0660
  notify: restart logstash

- name: Logstash | Start and Enable Service
  service:
    name: logstash
    state: started
    enabled: yes

- name: Logstash | Ensure Service is Running
  wait_for:
    port: "{{ ls_http_port }}"
    delay: 3
